// Generated by npm run examples:sync. New starter projects replace this module.
import { w3boosterApp as starter } from './w3booster.generated';
import { w3boosterApp as app0 } from './registered/match-dashboard';
import { w3boosterApp as app1 } from './registered/resource-monitor';
import { w3boosterApp as app2 } from './registered/settings-playground';
import { w3boosterApp as app3 } from './registered/clean-overlay';
export function getApplication(slug: string | null) {
  switch (slug) {
    case null: return starter;
    case 'match-dashboard': return app0;
    case 'resource-monitor': return app1;
    case 'settings-playground': return app2;
    case 'clean-overlay': return app3;
    default: throw new Error('Unknown example application. Open it from the W3Booster example catalog.');
  }
}
